---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-firehose
spec:
  selector:
    matchLabels:
      app: firehose
  template:
    metadata:
      labels:
        app: firehose
    spec:
      containers:
      - name: firehose
        image: "{{ .Values.firehose.image.repository }}:{{ .Values.firehose.image.tag }}"
        imagePullPolicy: Always
        imagePullSecrets:
        - name: dockerconfigjson-github-com
        env:
        - name: CHECKPOINT_METHOD
          value: "KeepermapUpdating"
        - name: PYTHONASYNCIODEBUG
          value: "1"
        - name: CLICKHOUSE_HOST
          value: {{ .Values.global.clickhouse.host | quote }}
        - name: CLICKHOUSE_PORT
          value: {{ .Values.global.clickhouse.port | quote }}
        - name: CLICKHOUSE_DATABASE
          value: {{ .Values.global.clickhouse.database | quote }}
        - name: CLICKHOUSE_USER
          value: {{ .Values.global.clickhouse.user | quote }}
        - name: CLICKHOUSE_PASSWORD
          value: {{ .Values.global.clickhouse.password | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag }}"
        imagePullSecrets:
        - name: dockerconfigjson-github-com
        ports:
        - containerPort: {{ .Values.webapp.port }}
        env:
        - name: CLICKHOUSE_HOST
          value: {{ .Values.global.clickhouse.host | quote }}
        - name: CLICKHOUSE_PORT
          value: {{ .Values.global.clickhouse.port | quote }}
        - name: CLICKHOUSE_DATABASE
          value: {{ .Values.global.clickhouse.database | quote }}
        - name: CLICKHOUSE_PASSWORD
          value: {{ .Values.global.clickhouse.password | quote }}
        - name: CLICKHOUSE_USER
          value: {{ .Values.global.clickhouse.user | quote }}
      - name: busybox
        image: busybox
        command: ["sleep", "infinity"]
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webapp
spec:
  selector:
    app: webapp
  ports:
  - port: {{ .Values.webapp.port }}
    targetPort: 8000
  type: ClusterIP
